# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\simple_file_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(22, 32, 751, 531))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.filepath_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.filepath_lineEdit.setObjectName("filepath_lineEdit")
        self.horizontalLayout.addWidget(self.filepath_lineEdit)
        self.change_path_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.change_path_pushButton.setObjectName("change_path_pushButton")
        self.horizontalLayout.addWidget(self.change_path_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.load_file_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.load_file_pushButton.setObjectName("load_file_pushButton")
        self.horizontalLayout_2.addWidget(self.load_file_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.content_plainTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.content_plainTextEdit.setObjectName("content_plainTextEdit")
        self.verticalLayout.addWidget(self.content_plainTextEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.save_file_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.save_file_pushButton.setObjectName("save_file_pushButton")
        self.horizontalLayout_3.addWidget(self.save_file_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "简单文件编辑"))
        self.label.setText(_translate("MainWindow", "文件路径"))
        self.filepath_lineEdit.setText(_translate("MainWindow", "./simple_file_edit.py"))
        self.change_path_pushButton.setText(_translate("MainWindow", "修改路径"))
        self.load_file_pushButton.setText(_translate("MainWindow", "加载文件"))
        self.save_file_pushButton.setText(_translate("MainWindow", "保存文件"))
